- name: Add Grafana repo
  yum_repository:
    name: Grafana
    description: Grafana Repository
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: yes
    gpgkey: https://packages.grafana.com/gpg.key

- name: Install Grafana package
  yum:
    name: [
      "grafana"
    ]
    state: present

- name: Start and enable Grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: Check if Grafana is accessible
  uri:
    url: http://localhost:3000
    method: GET
    status_code: 200
