- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever

- name: Install Nginx package
  yum:
    name: [
      "nginx",
      "policycoreutils-python"
    ]
    state: present

- name: Enable Nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Add default Nginx config template
  template:
    src: templates/etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Add Grafana site template to Nginx
  template:
    src: templates/etc/nginx/conf.d/grafana.conf.j2
    dest: /etc/nginx/conf.d/grafana.conf
  notify: restart_nginx

- name: Add SELinux exception for httpd_t
  ansible.builtin.command: "semanage permissive -a  httpd_t"

- name: Restart Nginx
  service:
    name: nginx.service
    state: restarted
