- name: Install NTP
  yum:
    name: ntp
    state: present

- name: Set timezone to GMT+2
  command: timedatectl set-timezone Etc/GMT-2

- name: Enable and start NTP service
  service:
    name: ntpd
    state: started
    enabled: yes

- name: Restart NTP service to apply new configuration
  service:
    name: ntpd
    state: restarted
